### ISSUE TITLE
Biosample Activity Downloads

### ISSUE THREAD

**Issue by Jill-Moore** [weng-lab/SCREEN2.0#373]
- [x] Can we give names to the download table from this page. Currently they are just table.tsv (Jonathan - use downloadFileName prop)
- [x] In the downloaded files DNase H3K4me3, and H3K27ac have rounded numbers (2 decimal places) same need to be down for ATAC.
- [x] Need to use "NA" for when no data is present, currently using "-11"
- [x] Classifications are incorrect 
![image](https://github.com/user-attachments/assets/a75a3a44-8f56-4921-bdfd-7491282a904f)

**Comment by GannaMohit** [comment]
1. Can we give names to the download table from this page. Currently they are just table.tsv (Jonathan - use downloadFileName prop): Changed the filename to the format "{assembly} {accession} - {table name}"
2. In the downloaded files DNase H3K4me3, and H3K27ac have rounded numbers (2 decimal places) same need to be down for ATAC.: Fixed the bug by changing the DataTable value function correctly to mimic the other scores.
3. Need to use "NA" for when no data is present, currently using "-11": This was automatically fixed by fixing the previous task, but it is displaying -- instead of -11.
